### ISSUE TITLE
Add measurements

### ISSUE THREAD

**Issue by alprema** [Abc-Arbitrage/Zebus.Directory#6]
There is currently no way to plug easily a metrics system into the Directory without creating a strong dependency, it would be useful to make it plugable so one can monitor Directories efficiently.

The interesting points to measure would be at least :
- Registration time
- Subscription update time
- Total subscription size in MB

**Comment by ltrzesniewski** [comment]
This issue was moved to Abc-Arbitrage/Zebus#72
